# SVM Classifcation Determining Whether Mushrooms are Edible or Poisonous

## Import libraries and prepare data

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
data = pd.read_csv('mushrooms.csv')
# data = data[data['stalk-root'] != '?'] # drop null values
data.drop(['stalk-root', 'veil-type'], axis=1, inplace=True) # drop column with null values
data = data.applymap(lambda x : (ord(x)-ord('a'))) # encode character values as it's unicode value minus unicode value of 'a'
data['class'] = data['class'].map({15:0, 4: 1}) # assign poisonous lable as 0 and edible lable as 1

data # preview data

class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         0         23           18         13       19    15   
1         1         23           18         24       19     0   
2         1          1           18         22       19    11   
3         0         23           24         22       19    15   
4         1         23           18          6        5    13   
...     ...        ...          ...        ...      ...   ...   
8119      1         10           18         13        5    13   
8120      1         23           18         13        5    13   
8121      1          5           18         13        5    13   
8122      0         10           24         13        5    24   
8123      1         23           18         13        5    13   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   5             2         13          10  ...   
1                   5             2          1          10  ...   
2                   5             2          1          13  ...   
3                   5             2         13          13  ...   
4                   5            22          1          10  ...   
...               ...           ...        ...         ...  ...   
8119                0             2          1          24  ...   
8120                0             2          1          24  ...   
8121                0             2          1          13  ...   
8122                5             2         13           1  ...   
8123                0             2          1          24  ...   

      stalk-surface-above-ring  stalk-surface-below-ring  \
0                           18                        18   
1                           18                        18   
2                           18                        18   
3                           18                        18   
4                           18                        18   
...                        ...                       ...   
8119                        18                        18   
8120                        18                        18   
8121                        18                        18   
8122                        18                        10   
8123                        18                        18   

      stalk-color-above-ring  stalk-color-below-ring  veil-color  ring-number  \
0                         22                      22          22           14   
1                         22                      22          22           14   
2                         22                      22          22           14   
3                         22                      22          22           14   
4                         22                      22          22           14   
...                      ...                     ...         ...          ...   
8119                      14                      14          14           14   
8120                      14                      14          13           14   
8121                      14                      14          14           14   
8122                      22                      22          22           14   
8123                      14                      14          14           14   

      ring-type  spore-print-color  population  habitat  
0            15                 10          18       20  
1            15                 13          13        6  
2            15                 13          13       12  
3            15                 10          18       20  
4             4                 13           0        6  
...         ...                ...         ...      ...  
8119         15                  1           2       11  
8120         15                  1          21       11  
8121         15                  1           2       11  
8122          4                 22          21       11  
8123         15                 14           2       11  

[8124 rows x 21 columns]

In [3]:
# split data into labels and features
labels = data['class']
features = data.drop('class', axis=1)

## Perform SVM with all features

In [4]:
# 80/20 split of data into training and testing data
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.20)

### Linear SVM

In [5]:
svclassifier = SVC(kernel='linear')
svclassifier.fit(train_features, train_labels)

label_pred = svclassifier.predict(test_features)

c = confusion_matrix(test_labels, label_pred)
error = (c[0][1]+c[1][0])/np.sum(c)

print(f'Prediction Error: {error}')
print(c)
print(classification_report(test_labels, label_pred))

Prediction Error: 0.040615384615384616
[[784  18]
 [ 48 775]]
              precision    recall  f1-score   support

           0       0.94      0.98      0.96       802
           1       0.98      0.94      0.96       823

    accuracy                           0.96      1625
   macro avg       0.96      0.96      0.96      1625
weighted avg       0.96      0.96      0.96      1625



### SVM with Quadratic Polynomial Kernel

In [6]:
svclassifier = SVC(kernel='poly',degree=2)
svclassifier.fit(train_features, train_labels)

label_pred = svclassifier.predict(test_features)

c = confusion_matrix(test_labels, label_pred)
error = (c[0][1]+c[1][0])/np.sum(c)

print(f'Prediction Error: {error}')
print(c)
print(classification_report(test_labels, label_pred))

Prediction Error: 0.0
[[802   0]
 [  0 823]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       802
           1       1.00      1.00      1.00       823

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625



### SVM with Cubic Polynomial Kernel

In [7]:
svclassifier = SVC(kernel='poly',degree=3)
svclassifier.fit(train_features, train_labels)

label_pred = svclassifier.predict(test_features)

c = confusion_matrix(test_labels, label_pred)
error = (c[0][1]+c[1][0])/np.sum(c)

print(f'Prediction Error: {error}')
print(c)
print(classification_report(test_labels, label_pred))

Prediction Error: 0.0
[[802   0]
 [  0 823]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       802
           1       1.00      1.00      1.00       823

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625



### SVM with Radial Basis Function (RBF) Kernel

In [8]:
svclassifier = SVC(kernel='rbf')
svclassifier.fit(train_features, train_labels)

label_pred = svclassifier.predict(test_features)

c = confusion_matrix(test_labels, label_pred)
error = (c[0][1]+c[1][0])/np.sum(c)

print(f'Prediction Error: {error}')
print(c)
print(classification_report(test_labels, label_pred))

Prediction Error: 0.0
[[802   0]
 [  0 823]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       802
           1       1.00      1.00      1.00       823

    accuracy                           1.00      1625
   macro avg       1.00      1.00      1.00      1625
weighted avg       1.00      1.00      1.00      1625



## Greedy Foward Feature Selection (with RBF kernel)

### Define function to perform greedy foward feature selection

In [9]:
def greedy_forward(data=data, labels=labels, features=features):
    attributes = features.columns
    selected = []
    min_error = (2.0, None)
    last_min_error = (1.0, None)

    # split data into training and test
    train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.20)
    while last_min_error < min_error or len(attributes) == 0: # still improving
        # compute error of SVM of selected + feat
        # add min error to selected IFF it reduces total error
        min_error = last_min_error
        for attr in attributes:
            temp = selected + [attr]
            svclassifier = SVC(kernel='rbf')
            svclassifier.fit(train_features[temp], train_labels)

            label_pred = svclassifier.predict(test_features[temp])

            c = confusion_matrix(test_labels, label_pred)
            error = (c[0][1]+c[1][0])/np.sum(c)
            
            if error < last_min_error[0]:
                last_min_error = (error, attr) 
            
        # add to selected
        if last_min_error[0] < min_error[0]:
            selected.append(last_min_error[1])
            attributes.drop(last_min_error[1])

    return selected

### Show results of a single greedy foward feature selection

In [10]:
greedy_attributes = greedy_forward()

greedy_attributes

['odor', 'spore-print-color']

### Perform same SVM classifiers as before with greedily selected features

In [11]:
greedy_features = data[greedy_attributes]
train_features, test_features, train_labels, test_labels = train_test_split(greedy_features, labels, test_size = 0.20)

### Linear SVM

In [12]:
svclassifier = SVC(kernel='poly',degree=2)
svclassifier.fit(train_features, train_labels)

label_pred = svclassifier.predict(test_features)

c = confusion_matrix(test_labels, label_pred)
error = (c[0][1]+c[1][0])/np.sum(c)

print(f'Prediction Error: {error}')
print(c)
print(classification_report(test_labels, label_pred))

Prediction Error: 0.32861538461538464
[[356 413]
 [121 735]]
              precision    recall  f1-score   support

           0       0.75      0.46      0.57       769
           1       0.64      0.86      0.73       856

    accuracy                           0.67      1625
   macro avg       0.69      0.66      0.65      1625
weighted avg       0.69      0.67      0.66      1625



### SVM with Quadratic Polynomial Kernel

In [13]:
svclassifier = SVC(kernel='poly',degree=2)
svclassifier.fit(train_features, train_labels)

label_pred = svclassifier.predict(test_features)

c = confusion_matrix(test_labels, label_pred)
error = (c[0][1]+c[1][0])/np.sum(c)

print(f'Prediction Error: {error}')
print(c)
print(classification_report(test_labels, label_pred))

Prediction Error: 0.32861538461538464
[[356 413]
 [121 735]]
              precision    recall  f1-score   support

           0       0.75      0.46      0.57       769
           1       0.64      0.86      0.73       856

    accuracy                           0.67      1625
   macro avg       0.69      0.66      0.65      1625
weighted avg       0.69      0.67      0.66      1625



### SVM with Cubic Polynomial Kernel

In [14]:
svclassifier = SVC(kernel='poly',degree=3)
svclassifier.fit(train_features, train_labels)

label_pred = svclassifier.predict(test_features)

c = confusion_matrix(test_labels, label_pred)
error = (c[0][1]+c[1][0])/np.sum(c)

print(f'Prediction Error: {error}')
print(c)
print(classification_report(test_labels, label_pred))

Prediction Error: 0.2966153846153846
[[339 430]
 [ 52 804]]
              precision    recall  f1-score   support

           0       0.87      0.44      0.58       769
           1       0.65      0.94      0.77       856

    accuracy                           0.70      1625
   macro avg       0.76      0.69      0.68      1625
weighted avg       0.75      0.70      0.68      1625



### SVM with RBF Kernel

In [15]:
svclassifier = SVC(kernel='rbf')
svclassifier.fit(train_features, train_labels)

label_pred = svclassifier.predict(test_features)

c = confusion_matrix(test_labels, label_pred)
error = (c[0][1]+c[1][0])/np.sum(c)

print(f'Prediction Error: {error}')
print(c)
print(classification_report(test_labels, label_pred))

Prediction Error: 0.010461538461538461
[[752  17]
 [  0 856]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       769
           1       0.98      1.00      0.99       856

    accuracy                           0.99      1625
   macro avg       0.99      0.99      0.99      1625
weighted avg       0.99      0.99      0.99      1625



## Sigmoid Kernel

### Sigmoid Kernel on Greedily Chosen Features

In [16]:
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(train_features, train_labels)

label_pred = svclassifier.predict(test_features)

c = confusion_matrix(test_labels, label_pred)
error = (c[0][1]+c[1][0])/np.sum(c)

print(f'Prediction Error: {error}')
print(c)
print(classification_report(test_labels, label_pred))

Prediction Error: 0.48738461538461536
[[371 398]
 [394 462]]
              precision    recall  f1-score   support

           0       0.48      0.48      0.48       769
           1       0.54      0.54      0.54       856

    accuracy                           0.51      1625
   macro avg       0.51      0.51      0.51      1625
weighted avg       0.51      0.51      0.51      1625



### Sigmoid Kernel on All Features

In [17]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.20)
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(train_features, train_labels)

label_pred = svclassifier.predict(test_features)

c = confusion_matrix(test_labels, label_pred)
error = (c[0][1]+c[1][0])/np.sum(c)

print(f'Prediction Error: {error}')
print(c)
print(classification_report(test_labels, label_pred))

Prediction Error: 0.5544615384615385
[[346 456]
 [445 378]]
              precision    recall  f1-score   support

           0       0.44      0.43      0.43       802
           1       0.45      0.46      0.46       823

    accuracy                           0.45      1625
   macro avg       0.45      0.45      0.45      1625
weighted avg       0.45      0.45      0.45      1625



In [18]:
norm_features = (features - features.min()) / (features.max() - features.min())

norm_features.head()

cap-shape  cap-surface  cap-color  bruises      odor  gill-attachment  \
0        1.0     0.684211   0.521739      1.0  0.625000              1.0   
1        1.0     0.684211   1.000000      1.0  0.000000              1.0   
2        0.0     0.684211   0.913043      1.0  0.458333              1.0   
3        1.0     1.000000   0.913043      1.0  0.625000              1.0   
4        1.0     0.684211   0.217391      0.0  0.541667              1.0   

   gill-spacing  gill-size  gill-color  stalk-shape  stalk-surface-above-ring  \
0           0.0        1.0    0.391304          0.0                  0.684211   
1           0.0        0.0    0.391304          0.0                  0.684211   
2           0.0        0.0    0.521739          0.0                  0.684211   
3           0.0        1.0    0.521739          0.0                  0.684211   
4           1.0        0.0    0.391304          1.0                  0.684211   

   stalk-surface-below-ring  stalk-color-above-ring  stalk-color-below-ring  \
0                  0.684211                0.913043                0.913043   
1                  0.684211                0.913043                0.913043   
2                  0.684211                0.913043                0.913043   
3                  0.684211                0.913043                0.913043   
4                  0.684211                0.913043                0.913043   

   veil-color  ring-number  ring-type  spore-print-color  population   habitat  
0    0.818182     0.166667        1.0           0.391304    0.750000  0.894737  
1    0.818182     0.166667        1.0           0.521739    0.541667  0.157895  
2    0.818182     0.166667        1.0           0.521739    0.541667  0.473684  
3    0.818182     0.166667        1.0           0.391304    0.750000  0.894737  
4    0.818182     0.166667        0.0           0.521739    0.000000  0.157895

In [19]:
train_features, test_features, train_labels, test_labels = train_test_split(norm_features, labels, test_size = 0.20)
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(train_features, train_labels)

label_pred = svclassifier.predict(test_features)

c = confusion_matrix(test_labels, label_pred)
error = (c[0][1]+c[1][0])/np.sum(c)

print(f'Prediction Error: {error}')
print(c)
print(classification_report(test_labels, label_pred))

Prediction Error: 0.5076923076923077
[[386 436]
 [389 414]]
              precision    recall  f1-score   support

           0       0.50      0.47      0.48       822
           1       0.49      0.52      0.50       803

    accuracy                           0.49      1625
   macro avg       0.49      0.49      0.49      1625
weighted avg       0.49      0.49      0.49      1625



In [20]:
train_features, test_features, train_labels, test_labels = train_test_split(norm_features[greedy_attributes], labels, test_size = 0.20)
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(train_features, train_labels)

label_pred = svclassifier.predict(test_features)

c = confusion_matrix(test_labels, label_pred)
error = (c[0][1]+c[1][0])/np.sum(c)

print(f'Prediction Error: {error}')
print(c)
print(classification_report(test_labels, label_pred))

Prediction Error: 0.4775384615384615
[[379 376]
 [400 470]]
              precision    recall  f1-score   support

           0       0.49      0.50      0.49       755
           1       0.56      0.54      0.55       870

    accuracy                           0.52      1625
   macro avg       0.52      0.52      0.52      1625
weighted avg       0.52      0.52      0.52      1625

